const POST_TYPE = {
    POST_LOADING: "POST_LOADING",
    POST_SUCCESS: "POST_SUCCESS",
    POST_FAIL: "POST_FAIL"
}

const DELETE_POST_TYPE = {
    DELETE_POST_LOADING: "DELETE_POST_LOADING",
    DELETE_POST_SUCCESS: "DELETE_POST_SUCCESS",
    DELETE_POST_FAIL: "DELETE_POST_FAIL"
}
const EDIT_POST_TYPE = {
    EDIT_POST_LOADING: "EDIT_POST_LOADING",
    EDIT_POST_SUCCESS: "EDIT_POST_SUCCESS",
    EDIT_POST_FAIL: "EDIT_POST_FAIL"
}

const ADD_POST_TYPE = {
    ADD_POST_LOADING: "ADD_POST_LOADING",
    ADD_POST_SUCCESS: "ADD_POST_SUCCESS",
    ADD_POST_FAIL: "ADD_POST_FAIL"
}

export { POST_TYPE, DELETE_POST_TYPE, EDIT_POST_TYPE, ADD_POST_TYPE }